### PR TITLE
fixes #656

### LINKED ISSUE #656: Bug in TimestampSkippingIterator
While running a long run of webindex on EC2 was seeing the following bug in the Accumulo monitor page.  The bug occurred at [TimeStampSkippingIterator line 106]( https://github.com/fluo-io/fluo/blob/10b69201d923edaecb91c39f919c6d7c296044a7/modules/accumulo/src/main/java/io/fluo/accumulo/iterators/TimestampSkippingIterator.java#L106)

```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Start key must be less than end key in range (um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [%00;] 9223372036854775807 false, um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [] -9223372036854775808 false)
	java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Start key must be less than end key in range (um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [%00;] 9223372036854775807 false, um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [] -9223372036854775808 false)
		at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler.continueMultiScan(TabletServer.java:680)
		at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler.startMultiScan(TabletServer.java:632)
		at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.accumulo.core.trace.wrappers.RpcServerInvocationHandler.invoke(RpcServerInvocationHandler.java:46)
		at org.apache.accumulo.server.rpc.RpcWrapper$1.invoke(RpcWrapper.java:74)
		at com.sun.proxy.$Proxy20.startMultiScan(Unknown Source)
		at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$startMultiScan.getResult(TabletClientService.java:2330)
		at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$startMultiScan.getResult(TabletClientService.java:2314)
		at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
		at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
		at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:63)
		at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:516)
		at org.apache.accumulo.server.rpc.CustomNonBlockingServer$1.run(CustomNonBlockingServer.java:78)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Start key must be less than end key in range (um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [%00;] 9223372036854775807 false, um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [] -9223372036854775808 false)
		at org.apache.accumulo.tserver.scan.ScanTask.get(ScanTask.java:126)
		at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler.continueMultiScan(TabletServer.java:667)
		... 18 more
	Caused by: java.lang.IllegalArgumentException: Start key must be less than end key in range (um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [%00;] 9223372036854775807 false, um:d:3d7:%03;%01;com.120sports>.www>o>%af; data:current [] -9223372036854775808 false)
		at org.apache.accumulo.core.data.Range.<init>(Range.java:175)
		at io.fluo.accumulo.iterators.TimestampSkippingIterator.skipColumn(TimestampSkippingIterator.java:106)
		at io.fluo.accumulo.iterators.SnapshotIterator.next(SnapshotIterator.java:155)
		at org.apache.accumulo.core.iterators.system.SourceSwitchingIterator.readNext(SourceSwitchingIterator.java:139)
		at org.apache.accumulo.core.iterators.system.SourceSwitchingIterator.next(SourceSwitchingIterator.java:123)
		at org.apache.accumulo.tserver.tablet.Tablet.lookup(Tablet.java:753)
		at org.apache.accumulo.tserver.tablet.Tablet.lookup(Tablet.java:848)
		at org.apache.accumulo.tserver.scan.LookupTask.run(LookupTask.java:113)
		at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
```

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: modules/accumulo/src/main/java/io/fluo/accumulo/iterators/TimestampSkippingIterator.java [hunk 1]
```diff
@@ -103,7 +103,13 @@ public void skipColumn(Key curCol) throws IOException {
         && curCol.equals(source.getTopKey(), PartialKey.ROW_COLFAM_COLQUAL_COLVIS)) {
       if (count == 10) {
         Key seekKey = curCol.followingKey(PartialKey.ROW_COLFAM_COLQUAL_COLVIS);
-        Range newRange = new Range(seekKey, true, range.getEndKey(), range.isEndKeyInclusive());
+        Range newRange;
+        if (range.afterEndKey(seekKey)) {
+          newRange =
+              new Range(range.getEndKey(), true, range.getEndKey(), range.isEndKeyInclusive());
```
Comment (mikewalch) [inline modules/accumulo/src/main/java/io/fluo/accumulo/iterators/TimestampSkippingIterator.java]: can you explain this?

Comment (keith-turner) [inline modules/accumulo/src/main/java/io/fluo/accumulo/iterators/TimestampSkippingIterator.java]: I added a comment to the code explaining the purpose.  Also the code was slightly incorrect.  

I wrote the following little test and it prints false three times.   I had to change the end key's inclusiveness to false to make sure it always prints false.

```java
    Key k0 = new Key("r1","fam1","q1",56437l);
    Key k1 = new Key("r1","fam1","q1",56436l);
    Key k2 = new Key("r1","fam1","q1",56435l);

    Range r1 = new Range(k1, true, k1, false);

    System.out.println(r1.contains(k0));
    System.out.println(r1.contains(k1));
    System.out.println(r1.contains(k2));
```

**Comment by mikewalch** [comment]
+1
