### PR TITLE
fixes #185 added findbugs check to pom and fixed bugs found

### LINKED ISSUE #185: Run findbugs as part of build
Automatically running findbugs as part of maven build would be very nice.  We can set the level and exclude thrift as was done in [ACCUMULO-2697][1]

[1]: https://issues.apache.org/jira/browse/ACCUMULO-2697

### PR DESCRIPTION
**Pull request by keith-turner**
The checked added to pom checks for findbugs ranks : scariest (rank 1-4), scary (rank 5-9).

### CODE REVIEW

File: modules/api/src/main/java/io/fluo/api/data/Bytes.java [hunk 1]
```diff
@@ -170,6 +171,7 @@ final public static Bytes of(byte[] array) {
    * @param length Number of bytes to include
    */
   final public static Bytes of(byte data[], int offset, int length) {
+    Preconditions.checkNotNull(data);
```
Comment (mikewalch) [inline modules/api/src/main/java/io/fluo/api/data/Bytes.java]: Should `final public static Bytes of(byte[] array)` have this check too?

Comment (keith-turner) [inline modules/api/src/main/java/io/fluo/api/data/Bytes.java]: added in bad29c4

**Comment by mikewalch** [comment]
+1
